version: '3'

services:
  mbp:
    container_name: mbp
    build: .
    links:
      - mosquitto
      - mongodb
      - iot-device
      - dashboard-frontend
    ports:
      - 8080:8080
    networks:
      default:
        ipv4_address: 172.16.238.08

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: amd64/mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_volume:/data/db

  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    build:
      context: ./mosquitto
      args:
        # NOTE: change this to use mosquitto setup with(out) auth plugin installed
        is_secure: "false"
    ports:
      - 1883:1883
      - 1884:1884
    volumes:
      - mosquitto_volume:/var/lib/mosquitto
    networks:
      default:
        ipv4_address: 172.16.238.03
  
  iot-device:
    container_name: iot-device
    build: ./testing/iot-device-dockerfile
    ports:
      - 22:22
    networks:
      default:
        ipv4_address: 172.16.238.10
  
  dashboard-frontend:
    container_name: dashboard-frontend
    build: ./scenario-dashboard
    ports:
      - 8081:8081
      
  dashboard-backend:
    container_name: dashboard-backend
    build: ./automated_requests
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:8080/mbp/api/users/login"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      default:
        ipv4_address: 172.16.238.09
    

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"

volumes:
  mosquitto_volume:
  mongodb_volume: